{
  "hash": "20ab8acd58ebc4768c450d4df9d32f9c",
  "result": {
    "engine": "knitr",
    "markdown": "---\nauthor: Jack Williams and Quinn Asena\n---\n\n# Novelty and no analogue futures {#sec-novelty}\n\n## Background {#sec-background}\n\nThe modern analogue technique (MAT) is a standard approach for making quantitative inferences about past vegetation and climate from fossil pollen data, and from many other forms of palaeoecological data [@chevalier2020; @williams2008; @gavin2003; @overpeck1985]. The MAT relies on reasoning by analogy [@jackson2004], in which it is assumed that two compositionally similar pollen assemblages were produced by similar plant communities, growing under similar environments. The similarity of pollen assemblages is determined by the calculation of dissimilarity metrics.\n\nThe MAT can also be thought of as a non-parametric statistical technique, called a $k$-nearest neighbours algorithm. It is a simple form of machine learning. Each fossil pollen assemblage is matched to 1 or more ($k$) modern pollen assemblages, then is assigned the ecological and environmental characteristics associated with those modern analogues. \n\nThe MAT is a popular approach for reconstructing past environments and climates, due to its relative simplicity and intuitive appeal. However, like any algorithm, if used unwisely, it can produce spurious results. More generally, when reasoning by analogy, be careful! Analogies are always incomplete and imperfect, and you must use your critical judgement to determine whether these imperfections are minor or serious.\n\nTo reconstruct past environments using the MAT, we need three datasets:\n\n1. Modern species assemblages.\n2. Modern environmental variables.\n3. Fossil species assemblages.\n\nThe MAT follows four basic steps:\n\n1. Calculate dissimilarities between a fossil species assemblage $i$ and all modern species assemblages in set $S$.\n2. Discard modern samples with dissimilarities greater than a threshold.\n3. Identify and retain the $k$ closest modern analogues.\n4. Average the environmental conditions associated with the modern analogues and assign them to fossil sample $i$.\n\nNote that we are taking a detour into palaeoclimatology for two reasons. First, because palaeoclimatic reconstructions are still a primary use for fossil pollen and other micropalaeontological data. Second, because the MAT and the `analogue` package, as a dissimilarity-based approach, also lets us explore the novelty of past communities, perhaps of more interest to palaeoecologists than inferred palaeoclimates!\n\nThe following section, @sec-datawrangle, takes you through some pretty advanced data wrangling required to match species names between the datasets we will use. However, if you prefer to skip all the wrangling and jump directly to the analyses in @sec-crossvalid, the data have been saved post-wrangling and can be loaded into R directly. Run the 'Jump point' code below and portal to @sec-crossvalid.\n\n::: {.callout-tip}\n# Jump point\nLoad the packages in the next section first, then unfold and run this code to restore the wrangled data and portal to @sec-crossvalid.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# One file holding everything the analysis sections use. It is written at the\n# end of the data wrangling section, so it cannot go stale relative to it.\nwrangled <- readRDS(\"./data/no-analogue-wrangled.rds\")\n\nmod_pol_harm    <- wrangled$mod_pol_harm     # modern pollen, harmonised, proportions\ndevils_harm     <- wrangled$devils_harm      # Devil's Lake, harmonised, proportions\ndevils_ages     <- wrangled$devils_ages      # one age per Devil's Lake sample\nmod_clim_filter <- wrangled$mod_clim_filter  # modern climate, aligned row for row\nmod_ids         <- wrangled$mod_ids          # NAMPD sample identifiers\nmod_sites       <- wrangled$mod_sites        # NAMPD site names and coordinates\n```\n:::\n\n:::\n\n\n## Getting started\n\n::: {.callout-note}\n# Packages required for this section\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load up the packages\n\nif (!require(\"pacman\")) install.packages(\"pacman\", repos=\"http://cran.r-project.org\")\npacman::p_load(dplyr, tidyr, readr, tibble, stringr, neotoma2, analogue)\n```\n:::\n\n\n:::\n\n## Data wrangling {#sec-datawrangle}\n\nIn this case, data are coming from two separate sources, NeotomaDB for the historic pollen data, and the North American Modern Pollen Database (NAMPD; @whitmore2005) for both the modern pollen and modern climate variables. These three datasets (Historic pollen, modern pollen, and modern climate data) are required for the MAT. To implement the MAT, the two pollen datasets must contain the same taxa and have identical names for each taxon. Some of the data wrangling required to get two matrices containing the same taxa with identical names for the correct region (as required by the MAT function) is fairly advanced. This type of wrangling is quite common in palaeoecological data-science as you may be dealing with, for example, raw data collected by individuals, or from different databases that are stored in inconsistent formats.\n\nReady to wrangle? Let’s get the data ready:\n\n::: {.callout-tip}\n# Respawn code\n\nThis is the same Devil's Lake download used in @sec-age-depth, so if you have run that chapter the file is already on disk.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Gated so the API is only contacted when the file is missing. Note the\n# datasettype filter: site 666 carries five datasets and one of them (3802)\n# is a modern POLLEN SURFACE SAMPLE rather than part of the core. Downloading\n# without the filter silently appends a modern sample to the top of a\n# 14,000 year record.\nif (!file.exists(\"./data/devils_dl.rds\")) {\n  devils_dl <- get_sites(siteid = 666) %>%\n    get_datasets(all_data = TRUE) %>%\n    neotoma2::filter(datasettype == \"pollen\") %>%\n    get_downloads()\n  saveRDS(devils_dl, \"./data/devils_dl.rds\")\n} else {\n  devils_dl <- readRDS(\"./data/devils_dl.rds\")\n}\n```\n:::\n\n\n:::\n\nThe download holds everything Neotoma has for the site. `samples()` pulls the counts out of it, and does that **locally**: the API was contacted by `get_downloads()` above, not here. We keep pollen counted as numbers of grains, from the ecological groups this analysis is about.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndevils_samples <- samples(devils_dl) %>%\n  dplyr::filter(ecologicalgroup %in% c(\"UPHE\", \"TRSH\"), # upland herbs, trees and shrubs\n                elementtype == \"pollen\",\n                units == \"NISP\")                        # counts, not percentages\n\ndplyr::n_distinct(devils_samples$variablename)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 52\n```\n\n\n:::\n:::\n\n\nNote that in the above code **no** taxa have been aggregated, and no proportions calculated. Both happen later. The harmonisation table below expects Neotoma's own names, so lumping *Pinus* here, as @sec-dissimilarity does for its single-site analysis, would leave the table unable to match any of the three pine taxa Devil's Lake actually records. And proportions are best calculated after dropping taxa, to avoid re-calculating.\n\nWe will use the North American Modern Pollen Database (NAMPD) to create modern analogues [@whitmore2005]. The NAMPD includes both modern surface pollen samples and climate measurements. It is not (yet) accessible through Neotoma, but a copy is saved in the data directory of this book, so we can read it from there. It is always good to keep your own copy of data you depend on: servers are not maintained forever, and datasets are sometimes revised or withdrawn.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_pol  <- read_csv(\"./data/nampd-pollen.csv\",  show_col_types = FALSE)\nmod_clim <- read_csv(\"./data/nampd-climate.csv\", show_col_types = FALSE)\n```\n:::\n\n\nGreat! Now we have our three datasets:\n\n1. Our site of interest (Devil's Lake palaeo data).\n2. Our modern pollen data.\n3. Our modern climate measurements.\n\nThe modern datasets include the whole of North America and need to be filtered for the Eastern US so that the taxa are relevant to those in Devil's Lake. We're first going to filter by longitude, then select by taxa so that we have a matching matrix of species between Devil's Lake palaeo-data and the modern surface samples from the NAMPD. We are going to keep all data East of 105°W, see @krause2019 and @williams2001 for details.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Several columns hold information the MAT does not use\n# Keep the site identifier and the taxon counts only.\nmod_pol_east <- mod_pol %>%\n  filter(LONDD >= -105) %>% # keep sites east of 105 degrees west\n  select(ID2, ABIES:XANTHIUM)   # ID2 plus the 134 taxon columns\n\n# The site names and coordinates are dropped by that select(), so keep a small\n# lookup table. We need it later to identify particular samples by name.\nmod_sites <- mod_pol %>%\n  select(ID2, SITENAME, LATDD, LONDD)\n```\n:::\n\n\nWe will also filter the modern climate records by the same ID to match the modern pollen records.\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_clim_filter <- mod_clim %>% \n  filter(ID2 %in% mod_pol_east$ID2)\n```\n:::\n\n\n### Harmonising the taxon names {#sec-harmonisation}\n\nNow the tricky part. The two datasets do not use the same taxon names, and they do not\nidentify pollen to the same taxonomic level. We have provided a harmonisation table that accounts for the differences between the two datasets to help with creating the matching historic/modern pollen matrices necessary for the MAT. Creating harmonisation tables that account for naming conventions and taxonomic resolution can be a big job, here are some examples of the challenges of matching databases:\n\n- Devil's Lake records *Picea* (spruce) to the species-level. The NAMPD splits *Picea* across three columns, `PICEAX` (i.e., undifferentiated, genus-level), `PICGLAUC` (*P. glauca*) and `PICMARIA` (*P. mariana*).\n- Devil's Lake records *Rhus*. The NAMPD has no *Rhus* column at all, but it does have\n  `ANACARDI`, the family *Rhus* belongs to. The two names share no letters, making them hard to find.\n- Devil's Lake records *Sarcobatus vermiculatus* to the species-level. The NAMPD has *Sarcobatus* to the genus-level.\n- The NAMPD's `RHAMNACEAE` column is not only Rhamnaceae. Its metadata says it combines\n  Rhamnaceae with Vitaceae.\n\nBefore the MAT can compare the two pollen datasets, every taxon must have the same naming convention down to the case! Although we have provided a table to crossreference databases, if you need to do this procedure for your own data, several decisions must be made along the way, which do not necessarily have a _right_ answer. Here are some examples of challenges we faced:\n\n\n1. **What are the dataset's naming conventions?** In the NAMPD a trailing `X`\n   usually marks an undifferentiated taxon, so `PINUSX` is \"Pinus - Pine undifferentiated\".\n   But the genus names `RUMEX` and `SALIX` also end in `X` and do not indicate undifferentiated taxa. The convention is documented in the workbook's `METADATA` sheet, and reading it is more reliable than inferring it from the codes.\n\n2. **Which taxa in which dataset have a finer taxonomic resolution and how do you handle it?**\n   *Picea* the NAMPD has a finer taxonomic resolution than Devil's Lake, so we summed the pollen counts to match the broader taxonomic resolution of Devil's Lake. For *Sarcobatus* Devil's Lake\n   has a finer taxonomic resolution, so we aggregated *Sarcobatus* to the genus level at Devil's Lake to match the NAMPD data.\n\n3. **What happens when no name match exists?** In some cases, the family-level was recorded but not the  genus- or species- level, for example, *Rhus* matches to the Anacardiaceae family, *Ilex* to Aquifoliaceae   family, and *Morus* to Moraceae family. These are particularly tricky to track down!\n\n4. **What do you do with taxa that have no counterpart?** Devil's Lake records\n   `Cannabaceae sensu stricto`, and the NAMPD has no Cannabaceae column, so those counts are\n   discarded. `Angiospermae undiff. (herbs)` is unidentified herbaceous pollen with no\n   equivalent, so it goes too. Both are decisions to record rather than problems to solve. It is important to note how impactful removing taxa is to the whole dataset.\n\nAn important point to note is that a name-matching algorithm cannot make ecological\ndecisions, and can entirely miss issues like *Rhus* matching to the Anacardiaceae family.\nThus, harmonisation tables, like the one below, require substantial curation!\n\n### Matching taxa with the harmonisation table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nharmonisation <- read_csv(\"./data/pollen-harmonisation.csv\", show_col_types = FALSE)\n\n# One row per harmonised taxon. Each side's original names sit in a single\n# plus-separated string, so the table stays short enough to read and check.\nharmonisation %>%\n  select(harmonised_taxon, devils_taxa, nampd_codes, decision) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   harmonised_taxon      devils_taxa           nampd_codes              decision\n   <chr>                 <chr>                 <chr>                    <chr>   \n 1 Abies                 Abies                 ABIES                    match   \n 2 Acer                  Acer                  ACERX+ACNEGUNA+ACPENSYL… sum     \n 3 Alnus                 Alnus                 ALCRISPA+ALNUSX+ALRUBRA… sum     \n 4 Amaranthaceae undiff. Amaranthaceae undiff. CHENOAMX                 match   \n 5 Ambrosia-type         Ambrosia-type         AMBROSIA                 match   \n 6 Amorpha-type          Amorpha-type          AMORPHA                  match   \n 7 Apiaceae              Apiaceae              APIACEAE                 match   \n 8 Artemisia             Artemisia             ARTEMISIA                match   \n 9 Asteraceae undiff.    Asteraceae undiff.    ASTERCICHO+ASTERX        sum     \n10 Betula                Betula                BETULA                   match   \n```\n\n\n:::\n:::\n\n\nThe `decision` column records what was done to each taxon: `match` for a straight\none-to-one, `sum` where several NAMPD columns roll up into one taxon, `coarsen` where Devil's\nLake was the finer of the two, and `drop` for the two taxa with no counterpart. Let's take the harmonisation table and transform it into one row per taxon for each dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nharm_nampd <- harmonisation %>%\n  filter(!is.na(nampd_codes)) %>% # Removs taxon that have no match\n  select(harmonised_taxon, nampd_codes) %>% # select only necessary columns\n  separate_longer_delim(nampd_codes, delim = \"+\") # split multiple names into individual rows\n\nharm_devils <- harmonisation %>%\n  filter(!is.na(harmonised_taxon)) %>%\n  select(harmonised_taxon, devils_taxa) %>%\n  separate_longer_delim(devils_taxa, delim = \"+\")\n\n# Check the dimensions of both datasets\ndim(harm_nampd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 70  2\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(harm_devils)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 50  2\n```\n\n\n:::\n:::\n\n\nCheck the output of each table relative to the original harmonisation table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(harm_nampd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  harmonised_taxon nampd_codes\n  <chr>            <chr>      \n1 Abies            ABIES      \n2 Acer             ACERX      \n3 Acer             ACNEGUNA   \n4 Acer             ACPENSYL   \n5 Acer             ACRUBRUM   \n6 Acer             ACSACNUM   \n```\n\n\n:::\n\n```{.r .cell-code}\nhead(harm_devils)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  harmonised_taxon      devils_taxa          \n  <chr>                 <chr>                \n1 Abies                 Abies                \n2 Acer                  Acer                 \n3 Alnus                 Alnus                \n4 Amaranthaceae undiff. Amaranthaceae undiff.\n5 Ambrosia-type         Ambrosia-type        \n6 Amorpha-type          Amorpha-type         \n```\n\n\n:::\n:::\n\n\nNow to implement harmonisation itself, which is the same operation on both datasets: pivot to long\nformat, join the table on, then sum the counts within each harmonised taxon. The `inner_join`\nis doing quiet but important work here, because any column absent from the table is dropped at\nthat step.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_pol_harm <- mod_pol_east %>%\n  pivot_longer(-ID2, names_to = \"nampd_codes\", values_to = \"count\") %>%\n  mutate(count = replace_na(count, 0)) %>%\n  inner_join(harm_nampd, by = \"nampd_codes\") %>%   # unmatched columns dropped here\n  group_by(ID2, harmonised_taxon) %>%\n  summarise(count = sum(count), .groups = \"drop\") %>%\n  pivot_wider(names_from = harmonised_taxon, values_from = count, values_fill = 0)\n\ndevils_harm <- devils_samples %>%\n  inner_join(harm_devils, by = c(\"variablename\" = \"devils_taxa\")) %>%\n  group_by(age, harmonised_taxon) %>%\n  summarise(count = sum(value), .groups = \"drop\") %>%\n  pivot_wider(names_from = harmonised_taxon, values_from = count, values_fill = 0)\n```\n:::\n\n\n::: {.callout-tip}\n# Good practice tip\nWhenever filtering or joining data it is good to check the dimensions before and after by using `dim()` to see if the results are what you expect. Some functions like `left_join()` or `full_join()` may run without error but produce unexpected results. It is also good to regularly use `rowSums()` to make sure you are using the correct data type (counts, proportions or percentages), and have not accidentally included age, depth, or ID columns if they should be excluded.\n:::\n\n\nTwo housekeeping steps before the analysis. The MAT needs the same taxa in the same order in\nboth matrices, and it needs the climate rows in the same order as the modern pollen rows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndevils_ages <- devils_harm$age\nmod_ids     <- mod_pol_harm$ID2\n\n# The climate data must line up row for row with the modern pollen, and the\n# MAT will not warn you if they do not. In this dataset they already match, but\n# only because the 94 rows with a missing ID2 also have a missing longitude and\n# are removed by the eastern filter. Do not rely on that: sort explicitly and\n# then check.\nmod_clim_filter <- mod_clim_filter %>%\n  arrange(match(ID2, mod_ids))\n\nstopifnot(identical(mod_clim_filter$ID2, mod_ids))\n\n# the same taxa, in the same order, on both sides\nshared       <- sort(intersect(names(mod_pol_harm), names(devils_harm)))\nmod_pol_harm <- as.matrix(mod_pol_harm[shared])\ndevils_harm  <- as.matrix(devils_harm[shared])\n```\n:::\n\n\n#### What the harmonisation cost\n\nHarmonising always loses something, and it is worth reporting how much rather than hoping\nnobody asks. Both matrices still hold counts at this point, so we can compare them against\nwhat we started with.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  dataset       = c(\"Devil's Lake\", \"NAMPD\"),\n  taxa_before   = c(n_distinct(devils_samples$variablename), ncol(mod_pol_east) - 1),\n  taxa_after    = length(shared),\n  grains_before = c(sum(devils_samples$value), sum(mod_pol_east[-1], na.rm = TRUE)),\n  grains_after  = c(sum(devils_harm), sum(mod_pol_harm))\n) %>%\n  mutate(pct_kept = round(100 * grains_after / grains_before, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  dataset      taxa_before taxa_after grains_before grains_after pct_kept\n  <chr>              <dbl>      <int>         <dbl>        <dbl>    <dbl>\n1 Devil's Lake          52         50        77999        77820      99.8\n2 NAMPD                134         50      1456810.     1351550.     92.8\n```\n\n\n:::\n:::\n\n\nThis is pretty good! We kept almost all of the taxa present in Devil's Lake, only two of its taxa had no counterpart. The reduction of species in the NAMPD is no surprise given that the data cover the entire eastern U.S. It is also worth seeing which taxa the aggregation changed most, since that is where the\nharmonisation had the largest effect on the modern data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nharmonisation %>%\n  filter(decision == \"sum\") %>%\n  select(harmonised_taxon, nampd_codes) %>%\n  mutate(n_columns = str_count(nampd_codes, fixed(\"+\")) + 1) %>%\n  arrange(desc(n_columns))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 3\n  harmonised_taxon   nampd_codes                                       n_columns\n  <chr>              <chr>                                                 <dbl>\n1 Acer               ACERX+ACNEGUNA+ACPENSYL+ACRUBRUM+ACSACNUM+ACSACR…         6\n2 Alnus              ALCRISPA+ALNUSX+ALRUBRA+ALRUGOSA                          4\n3 Ericaceae          ERICACEX+ERILEDCH+ERIVACCI                                3\n4 Fraxinus           FRAXINUX+FRAXNIGR+FRAXPNAM                                3\n5 Juglans            JUGCINER+JUGLANSX+JUGNIGRA                                3\n6 Picea              PICEAX+PICGLAUC+PICMARIA                                  3\n7 Tsuga              TSUGAX+TSUGHETE+TSUGMERT                                  3\n8 Asteraceae undiff. ASTERCICHO+ASTERX                                         2\n9 Rumex              RUMEOXYR+RUMEX                                            2\n```\n\n\n:::\n:::\n\n\n::: {#exr-pollen-or-spore}\nThe cost table says the NAMPD kept 92.8% of its pollen, so harmonisation discarded 7.2%. That sounds like a lot to lose to a join on taxon names. Find out what it actually was.\n\nThe `inner_join` in `harmoniseDatasets` dropped every NAMPD column with no row in the harmonisation table, silently and without a message. Those columns are the difference between the two sets of names. The NAMPD also documents what every one of its codes means, and the book ships that sheet, so here are both tools:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# the columns the join threw away\nunmapped <- setdiff(names(mod_pol_east)[-1], harm_nampd$nampd_codes)\nlength(unmapped)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 64\n```\n\n\n:::\n\n```{.r .cell-code}\n# what each NAMPD code actually is\nnampd_meta <- read_csv(\"./data/nampd-metadata.csv\", skip = 41,\n                       col_names = FALSE, show_col_types = FALSE) %>%\n  select(code = 1, description = 3) %>%\n  filter(!is.na(code))\n```\n:::\n\n\n1. Work out how many grains each of those columns holds and turn that into a percentage of the modern pollen sum. The denominator the cost table used is `sum(mod_pol_east[-1], na.rm = TRUE)`. Sort your answer so the largest losses come first.\n\n2. Take the eight largest and look each one up in `nampd_meta`. Search for any whose description you do not recognise, and for each decide whether the plant produces **pollen** or **spores**.\n\n3. The eight are not all the same kind of thing. Add up the share held by the spore and bryophyte producers. How much of the 7.2% do they account for, and how much is left over as a genuine loss of pollen taxa?\n\n4. Now the judgement. Devil's Lake was filtered with `elementtype == \"pollen\"` and to the ecological groups `UPHE` and `TRSH` at the start of this section. Run `table(samples(devils_dl)$elementtype)` to see what that filter removed, and `unique(samples(devils_dl)$variablename[samples(devils_dl)$elementtype == \"spore\"])` to see how those spores were recorded. Given what you find, is dropping the spore columns from the modern data a loss at all? What would have gone wrong if we had kept them?\n:::\n\n#### Converting to proportions\n\nSo far, we have been dealing with raw count data but, for the MAT, we need to convert to proportions, and the order matters. Squared chord distance is not\nscale invariant, so if the rows do sum to one the two datasets are not comparable: a\nfossil sample whose remaining taxa add up to 0.6 would look artificially far from every modern\nsample. Dividing before dropping columns is a common and quiet way to get this wrong, but `rowSums()` provides an easy check!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Take care that you do not accidentally include an age or depth column\n# when calculating proportions!\nmod_pol_harm <- mod_pol_harm / rowSums(mod_pol_harm)\ndevils_harm  <- devils_harm  / rowSums(devils_harm)\n\n# the same data check used in the dissimilarity chapter: both should be exactly 1\nrange(rowSums(mod_pol_harm))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1 1\n```\n\n\n:::\n\n```{.r .cell-code}\nrange(rowSums(devils_harm))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1 1\n```\n\n\n:::\n:::\n\n\nThat is the end of the wrangling. Everything the analysis needs is now in RAM, so we save it to disk in one object. We keep all necessary data saved so that all the resources you need exist offline and no API calls are needed to the Neotoma DB (which occasionally undergoes maintenance).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Written every time this chapter runs, not guarded with file.exists(). These\n# objects are derived from the code above, so a guard would let the saved file\n# drift out of step with the chapter while still looking fine.\nsaveRDS(list(mod_pol_harm    = mod_pol_harm,\n             devils_harm     = devils_harm,\n             devils_ages     = devils_ages,\n             mod_clim_filter = mod_clim_filter,\n             mod_ids         = mod_ids,\n             mod_sites       = mod_sites),\n        \"./data/no-analogue-wrangled.rds\")\n```\n:::\n\n\n\n## The Modern Analogue Technique\n\nNow that we have the data we need, and in the format that we need it, we can apply the MAT. If you portaled here and skipped the Data Wrangling in @sec-datawrangle, make sure you load in the pre-formatted data from the jump point in @sec-background.\n\n### Cross-validation {#sec-crossvalid}\n\nThe Modern Analogue Technique needs the same set of taxa in the modern dataset and in the historic pollen data. In @sec-harmonisation we produced: two matrices, `mod_pol_harm` and `devils_harm`, with identical columns names (taxa names) and rows that sum to one (relative abundances rather than raw pollen counts). Before reconstructing environmental variables from fossil pollen assemblages, we usually assess how MAT performs in the modern species assemblage. This step is usually referred to as calibration or cross-validation.\n\nIn cross-validation, a calibration function is trained on one portion of the modern species assemblages (calibration set) and applied to another portion of the modern species assemblages (validation set). These two datasets are thus mutually exclusive and, possibly, independent. To cross-validate MAT, we usually use a technique called $k$-fold cross-validation. In $k$-fold cross-validation the modern dataset is split into $k$ mutually exclusive subsets. For each $k^{th}$ subset, the calibration dataset comprises all the samples not in $k$, while the samples in $k$ comprise the validation dataset. The simplest form of $k$-fold cross-validation is the leave-one-out (LOO) technique, in which just a single sample is removed and then all other samples are used to build a prediction for that sample. This procedure is then repeated for all samples. The `analogue` package uses leave-one-out cross-validation. To assess the model, we can use standard metrics including root mean square error (RMSE) and $R^2$. Here, we’ll use the cross-validation tools built into the analogue package.\n\nNote that the `palaeoSig` package, developed by Richard Telford, has additional functions that can test for significance relative to randomly generated variables with the same spatial structure as the environmental variable of interest. We won’t use this package in this chapter, but it’s useful for testing whether apparently strong cross-validation results are merely an artefact of spatial autocorrelation [@telford2005].\n\nNow let's do the analysis! First is the cross-validation of the modern datasets. Using the modern data, we’ll build a calibration dataset and run cross-validation analyses of the calibration dataset. For simplicity, we are going to use January temperatures `tjan` as our climate variable:\n\n\n::: {.panel-tabset}\n\n## Code\n\n::: {.cell}\n\n```{.r .cell-code}\n# Select Jan temps\nmod_jant <- data.matrix(mod_clim_filter$tjan)\n# Fit the MAT using only the modern pollen. Named `modpoll_all` because it uses\n# every modern sample; we are about to find a problem with one of them.\nmodpoll_all <- analogue::mat(mod_pol_harm, mod_jant, method = \"SQchord\")\n```\n:::\n\n\n## Summary\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(modpoll_all)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tModern Analogue Technique\n\nCall:\nmat(x = mod_pol_harm, y = mod_jant, method = \"SQchord\") \n\nPercentiles of the dissimilarities for the training set:\n\n   1%    2%    5%   10%   20% \n0.153 0.203 0.299 0.404 0.562 \n\nInferences based on the mean of k-closest analogues:\n\n  k  RMSEP     R2 Avg Bias Max Bias\n  1  3.273  0.908   -0.219    2.625\n  2  2.933  0.925   -0.262    3.309\n  3  2.897  0.927   -0.293    3.332\n  4  2.877  0.927   -0.302    3.218\n  5  2.869  0.928   -0.317    3.336\n  6  2.885  0.927   -0.324    3.597\n  7  2.902  0.926   -0.314    3.825\n  8  2.961  0.923   -0.321    4.181\n  9  3.002  0.921   -0.348    4.291\n 10  3.010  0.921   -0.356    4.324\n\nInferences based on the weighted mean of k-closest analogues:\n\n  k RMSEP   R2 Avg Bias Max Bias\n  1   NaN   NA      NaN     2.62\n  2   NaN   NA      NaN     3.17\n  3   NaN   NA      NaN     3.21\n  4   NaN   NA      NaN     3.14\n  5   NaN   NA      NaN     3.21\n  6   NaN   NA      NaN     3.42\n  7   NaN   NA      NaN     3.59\n  8   NaN   NA      NaN     3.85\n  9   NaN   NA      NaN     3.94\n 10   NaN   NA      NaN     3.98\n```\n\n\n:::\n:::\n\n\n## Plot\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nplot(modpoll_all)\n```\n\n::: {.cell-output-display}\n![Cross-validation diagnostics for the modern analogue technique applied to mean January temperature, using all 2,594 modern samples. Observed against predicted, the residuals, and the effect of the number of analogues $k$.](no-analogue_files/figure-html/fig-mat-diagnostics-1.png){#fig-mat-diagnostics width=672}\n:::\n:::\n\n\n:::\n\nNotice anything off in the summary output?\n\n::: {.callout-warning}\n# Oh no! :scream:\n\nThe first table, the plain mean of the $k$ closest analogues, looks fine. The second table, the\n**weighted** mean, is entirely `NaN`:\n\n```r\nInferences based on the weighted mean of k-closest analogues:\n\n  k RMSEP   R2 Avg Bias Max Bias\n  1   NaN   NA      NaN     2.88\n  2   NaN   NA      NaN     3.74\n```\n\nNo error or warning... This is the most dangerous class of error in the book: no error message, and a plausible-looking answer sitting right next to a broken one. Always read the whole output. The cause is that weighting by *inverse* dissimilarity requires every dissimilarity to be\ngreater than zero.\n\n:::\n\nTwo of the 2,594 modern samples have **identical** pollen assemblages, so\nthe dissimilarity between them is exactly zero, and one divided by zero is undefined. That\nsingle pair poisons the whole weighted-mean column.\n\nSo find the duplicate rather than working around it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# duplicated() works row-wise on a matrix. Round first, because two assemblages\n# can be identical in every practical sense and still differ in the last bit of\n# floating-point representation.\nduplicate_rows <- duplicated(round(mod_pol_harm, 8))\nsum(duplicate_rows)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# which sites are they? mod_sites holds the names and coordinates\ntibble(ID2 = mod_ids[duplicate_rows | duplicated(round(mod_pol_harm, 8),\n                                                 fromLast = TRUE)]) %>%\n  left_join(mod_sites, by = \"ID2\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n    ID2 SITENAME LATDD LONDD\n  <dbl> <chr>    <dbl> <dbl>\n1   561 Mueller   45.2 -88.9\n2  2871 38        45.2 -89.0\n```\n\n\n:::\n:::\n\n\nTwo surface samples about 5.5 km apart, recorded under different site names, with pollen\nassemblages identical to eight decimal places. Whether that is two genuinely indistinguishable\nsites or the same sample entered twice by different contributors is a question for whoever\ncurates the database. Either way we cannot use both.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkeep <- !duplicated(round(mod_pol_harm, 8))\n\n# New objects rather than overwriting the old ones. The full matrices stay\n# available, which makes the two models comparable and means re-running this\n# chunk cannot quietly drop a second row.\nmod_pol_unique  <- mod_pol_harm[keep, , drop = FALSE]\nmod_clim_unique <- mod_clim_filter[keep, ]\n\ndim(mod_pol_harm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2594   50\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(mod_pol_unique)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2593   50\n```\n\n\n:::\n:::\n\n\nDropping one sample of 2,594 leaves the mean-based results untouched, so nothing is lost by\nbeing careful here: RMSEP at $k = 1$ moves from 3.379 to 3.380. Now, let's refit the model and check the output again:\n\n::: {.panel-tabset}\n\n## Code\n\n::: {.cell}\n\n```{.r .cell-code}\n# Select Jan temps for the samples we kept\nmod_jant_unique <- data.matrix(mod_clim_unique$tjan)\n# Refit. This is the model the rest of the chapter uses.\nmodpoll_jant <- analogue::mat(mod_pol_unique, mod_jant_unique, method = \"SQchord\")\n```\n:::\n\n\n## Summary\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(modpoll_jant)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tModern Analogue Technique\n\nCall:\nmat(x = mod_pol_unique, y = mod_jant_unique, method = \"SQchord\") \n\nPercentiles of the dissimilarities for the training set:\n\n   1%    2%    5%   10%   20% \n0.153 0.203 0.299 0.404 0.562 \n\nInferences based on the mean of k-closest analogues:\n\n  k  RMSEP     R2 Avg Bias Max Bias\n  1  3.274  0.908   -0.219    2.625\n  2  2.933  0.925   -0.262    3.309\n  3  2.897  0.927   -0.293    3.332\n  4  2.878  0.927   -0.302    3.218\n  5  2.870  0.928   -0.317    3.336\n  6  2.885  0.927   -0.324    3.597\n  7  2.902  0.926   -0.314    3.825\n  8  2.961  0.923   -0.322    4.181\n  9  3.003  0.921   -0.348    4.291\n 10  3.010  0.921   -0.356    4.324\n\nInferences based on the weighted mean of k-closest analogues:\n\n  k  RMSEP     R2 Avg Bias Max Bias\n  1  3.274  0.908   -0.219    2.625\n  2  2.883  0.927   -0.256    3.168\n  3  2.814  0.931   -0.279    3.206\n  4  2.770  0.933   -0.291    3.138\n  5  2.751  0.934   -0.301    3.205\n  6  2.751  0.934   -0.306    3.418\n  7  2.764  0.933   -0.301    3.595\n  8  2.793  0.932   -0.310    3.853\n  9  2.827  0.930   -0.330    3.939\n 10  2.833  0.930   -0.337    3.975\n```\n\n\n:::\n:::\n\n\n## Plot\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nplot(modpoll_jant)\n```\n\n::: {.cell-output-display}\n![The same diagnostics after removing the duplicated modern sample. Compare with @fig-mat-diagnostics: the mean-based results are unchanged, but the weighted mean is now defined.](no-analogue_files/figure-html/fig-mat-diagnostics-refit-1.png){#fig-mat-diagnostics-refit width=672}\n:::\n:::\n\n\n:::\n\n\n\n::: {#exr-choosing-k}\nThe summary for `modpoll_jant` reports RMSEP, $R^2$ and bias for every $k$ from 1 to 10, and the reconstruction later in this chapter is built with `k = 10`.\n\n1. Read off the $k$ that minimises RMSEP, once for the mean and once for the weighted mean. Does the same $k$ win in both cases?\n\n2. Rebuild the reconstruction with the $k$ you chose, using `predict(modpoll_jant, devils_harm, k = ...)`, and plot it against the `k = 10` version. How much does the choice actually change the reconstructed temperatures?\n\n3. RMSEP falls as $k$ increases and then rises again. Explain both halves of that curve: what goes wrong when too few analogues are averaged, and what goes wrong when too many are?\n:::\n\n::: {#exr-climate-variables}\nJanuary temperature is only one of the 69 climate variables in `mod_clim_filter`. Four others worth trying are `tjul` (July temperature), `pjul` (July precipitation), `gdd5` (growing degree days above 5°C, a measure of the length and warmth of the growing season) and `mipt` (an index of soil moisture availability). Note that the column names are lower case.\n\n1. Refit the MAT for each one, by swapping the variable in `data.matrix(mod_clim_filter$tjan)` and rerunning `analogue::mat()`. Record RMSEP and $R^2$ each time.\n\n2. Rank the four by predictive skill. Given what you know about which aspects of climate actually control where plants grow, and about how precisely each of these variables can be measured in the first place, is that ranking surprising? Say why.\n:::\n\nMuch of the information in this chapter comes from @simpson2007, and we recommend @simpson2007 for the interpretation of the outputs. The MAT method shares similar considerations as calculating dissimilarity (@sec-dissimilarity). With some additional considerations regarding transfer functions:\n\n\n### Novelty and palaeoclimatic reconstruction\n\nNow that we have cross-validated our model on modern samples, we can apply it to the historic pollen assemblage data from Devil's Lake. The following code calculates and plots the dissimilarity, number of modern analogues, and an inferred temperature reconstruction.\n\n::: {.panel-tabset}\n\n## Minimum distance\n\nConstruct a time series of the minimum SCDs (novelty) for Devil’s Lake.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predict temperatures from the fossil data and their modern analogues.\n# Kept separate from the plot below so that the objects survive even if a\n# figure chunk is switched off.\ndevil_jant   <- predict(modpoll_jant, devils_harm, k = 10)\ndevil_mindis <- minDC(devil_jant)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\nplot(devil_mindis, depths = devils_ages, quantiles = FALSE,\n     xlab = \"Age (yr BP)\", ylab = \"minSCD\")\n```\n\n::: {.cell-output-display}\n![Novelty at Devil's Lake through time, measured as the minimum squared chord distance between each fossil sample and its closest modern analogue. Higher values mean the assemblage is less like anything growing in eastern North America today.](no-analogue_files/figure-html/fig-devils-novelty-1.png){#fig-devils-novelty width=672}\n:::\n:::\n\n\n\n## Modern analogues\n\nConstruct a time series of the number of modern analogues found per fossil sample, using 0.25 as our no-analogue/analogue threshold. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndevil_cma <- analogue::cma(devil_jant, cutoff = 0.25)\n\n# how many fossil samples have no modern analogue at all?\nsum(devil_cma$n.analogs == 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 36\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(x = devils_ages, y = devil_cma$n.analogs, type = \"l\",\n     xlim = rev(range(devils_ages)),\n     xlab = \"Age (yr BP)\", ylab = \"Number of modern analogues\")\n```\n\n::: {.cell-output-display}\n![The number of modern analogues found for each Devil's Lake sample, using a squared chord distance of 0.25 as the threshold. Samples with none are the no-analogue assemblages.](no-analogue_files/figure-html/fig-devils-analogues-1.png){#fig-devils-analogues width=672}\n:::\n:::\n\n\n## Reconstruction\n\nPlot the reconstructed January temperatures at Devil's Lake:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreconPlot(devil_jant, depth = devils_ages, display.error = \"bars\",\n          xlab = \"Age (yr BP)\", ylab = \"Mean Jan temperature\")\n```\n\n::: {.cell-output-display}\n![Mean January temperature at Devil's Lake reconstructed with the modern analogue technique, with error bars. Compare the high-novelty intervals in @fig-devils-novelty before trusting any part of this curve.](no-analogue_files/figure-html/fig-devils-reconstruction-1.png){#fig-devils-reconstruction width=672}\n:::\n:::\n\n\n:::\n\n\n::: {#exr-nearby-site}\nDevil's Lake is a single record. A reconstruction is far more convincing if a nearby site tells the same story.\n\n1. Find another pollen site within a few hundred kilometres of Devil's Lake using the search methods in @sec-neotoma2, and download it with the same gated pattern as the respawn code above. Remember the `datasettype` filter.\n\n2. Put it through the harmonisation table and the MAT, then plot its reconstruction against the Devil's Lake one.\n\n3. The harmonisation table was built for Devil's Lake, so its `devils_taxa` column lists that site's taxa and no others. Find what your site records that the table has no row for. How much pollen does that cost you, and does it change how much you trust the comparison?\n:::\n\n### Limitations\n\nSimilar to the dissimilarity calculations in @sec-dissimilarity:\n\n- Chronological uncertainties are not accounted for. See @sec-age-depth for how the timing of ecological events may change based on the age-depth model.\n- Time averaging is not taken into account, and each sample may contain a different time-span of ecological productivity.\n- Squared chord distance is one of many distance measures available in `analogue`, and may not always be the most appropriate.\n\nAdditionally, transfer functions can themselves be problematic with circular reasoning using vegetation assemblages to infer climate and also inferring how climate affects vegetation! For deeper considerations of reconstructing temperatures using transfer functions see @telford2005.\n\n\n## Conclusion\n\nRemember that a limitation of dissimilarity measures was the lack of covariate data? The MAT includes modern climate combined with modern pollen to predict historic climate. We are now introducing environmental covariates into our analyses!\n\nThe exercises take that further, and are worth returning to if you skipped them:\n\n- @exr-pollen-or-spore, what the harmonisation actually discarded\n- @exr-choosing-k, how many analogues to average over\n- @exr-climate-variables, and which aspects of climate pollen can actually predict\n- @exr-nearby-site, applying the whole workflow to a second record\n",
    "supporting": [
      "no-analogue_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}